import { user } from "./types";

export const users: user[] = [
  {
    id: 0,
    fullname: "Abdelrahman Yasser",
    email: "abdelrahman@example.com",
    password: "Password123!",
    country: "Egypt",
    city: "New Cairo",
    streetAddress: "90th Street, 5th Settlement",
    apartment: "Apt 4B",
    zip: "11835",
    phoneNumber: "+201012345678",
  },
  {
    id: 1,
    fullname: "Sarah Ahmed",
    email: "sarah.ahmed@example.com",
    password: "SecurePass456!",
    country: "Egypt",
    city: "Alexandria",
    streetAddress: "15 Corniche Road",
    apartment: "Floor 3, Apt 12",
    zip: "21500",
    phoneNumber: "+201234567890",
  },
  {
    id: 2,
    fullname: "John Doe",
    email: "john.doe@test.com",
    password: "MySecretPass88@",
    country: "United States",
    city: "New York",
    streetAddress: "123 Broadway Ave",
    apartment: "Suite 101",
    zip: "10001",
    phoneNumber: "+15550199888",
  },
  {
    id: 3,
    fullname: "Layla Hassan",
    email: "layla.h@demo.com",
    password: "LaylaPass2024#",
    country: "UAE",
    city: "Dubai",
    streetAddress: "Sheikh Zayed Road",
    apartment: "Villa 45",
    zip: "00000",
    phoneNumber: "+971501234567",
  },
  {
    id: 4,
    fullname: "Mohamed Ali",
    email: "m.ali@work.net",
    password: "ProjectZ!99",
    country: "Egypt",
    city: "Giza",
    streetAddress: "Pyramids Gardens, Gate 2",
    apartment: "Building 15, Apt 2",
    zip: "12555",
    phoneNumber: "+201155667788",
  },
];
