import express from "express";
import mongoose from "mongoose";
import Product from "../models/Product.ts";

const sampleProducts = [
  {
    title: "Essence Mascara Lash Princess",
    brand: "Essence",
    price: 9.99,
    quantity: 99,
    soldQuantity: 0,
    rate: "2.56",
    discount: 10.48,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
    sku: "BEA-ESS-ESS-001",
    category: "beauty",
    colors: ["black", "brown"],
    description:
      "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    specifications: [
      "Waterproof",
      "Cruelty-free",
      "Long-lasting formula",
      "Volumizing effect",
    ],
    reviews: [
      {
        author: "Eleanor Collins",
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Lucas Gordon",
        rating: 4,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Eleanor Collins",
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Popular mascara for volumizing and lengthening lashes",
  },
  {
    title: "Eyeshadow Palette with Mirror",
    brand: "Glamour Beauty",
    price: 19.99,
    quantity: 34,
    soldQuantity: 0,
    rate: "2.86",
    discount: 18.19,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
    sku: "BEA-GLA-EYE-002",
    category: "beauty",
    colors: ["neutral", "warm", "cool"],
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    specifications: [
      "12 shades",
      "Built-in mirror",
      "Matte and shimmer finishes",
      "Long-wearing",
    ],
    reviews: [
      {
        author: "Savannah Gomez",
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Christian Perez",
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nicholas Bailey",
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Versatile eyeshadow palette with built-in mirror",
  },
  {
    title: "Powder Canister",
    brand: "Velvet Touch",
    price: 14.99,
    quantity: 89,
    soldQuantity: 0,
    rate: "4.64",
    discount: 9.84,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
    sku: "BEA-VEL-POW-003",
    category: "beauty",
    colors: ["translucent", "light", "medium"],
    description:
      "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    specifications: [
      "Translucent formula",
      "Oil-control",
      "Finely milled",
      "Matte finish",
    ],
    reviews: [
      {
        author: "Alexander Jones",
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Elijah Cruz",
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Avery Perez",
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Finely milled setting powder for matte finish",
  },
  {
    title: "Red Lipstick",
    brand: "Chic Cosmetics",
    price: 12.99,
    quantity: 91,
    soldQuantity: 0,
    rate: "4.36",
    discount: 12.16,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
    sku: "BEA-CHI-LIP-004",
    category: "beauty",
    colors: ["true red", "berry red", "crimson"],
    description:
      "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    specifications: [
      "Creamy formula",
      "Long-lasting",
      "Highly pigmented",
      "Moisturizing",
    ],
    reviews: [
      {
        author: "Liam Garcia",
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Ruby Andrews",
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Clara Berry",
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Classic red lipstick with creamy, pigmented formula",
  },
  {
    title: "Red Nail Polish",
    brand: "Nail Couture",
    price: 8.99,
    quantity: 79,
    soldQuantity: 0,
    rate: "4.32",
    discount: 11.44,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
    sku: "BEA-NAI-NAI-005",
    category: "beauty",
    colors: ["classic red", "ruby red", "cherry red"],
    description:
      "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    specifications: [
      "Quick-drying",
      "Glossy finish",
      "Chip-resistant",
      "Salon-quality",
    ],
    reviews: [
      {
        author: "Benjamin Wilson",
        rating: 2,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Liam Smith",
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Clara Berry",
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Rich red nail polish with quick-drying formula",
  },
  {
    title: "Calvin Klein CK One",
    brand: "Calvin Klein",
    price: 49.99,
    quantity: 29,
    soldQuantity: 0,
    rate: "4.37",
    discount: 1.89,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
    sku: "FRA-CAL-CAL-006",
    category: "fragrances",
    colors: ["clear"],
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    specifications: [
      "Unisex fragrance",
      "100ml",
      "Eau de Toilette",
      "Fresh scent",
    ],
    reviews: [
      {
        author: "Layla Young",
        rating: 2,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Daniel Cook",
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Jacob Cooper",
        rating: 3,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Classic unisex fragrance with fresh, clean scent",
  },
  {
    title: "Chanel Coco Noir Eau De",
    brand: "Chanel",
    price: 129.99,
    quantity: 58,
    soldQuantity: 0,
    rate: "4.26",
    discount: 16.51,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
    sku: "FRA-CHA-CHA-007",
    category: "fragrances",
    colors: ["black"],
    description:
      "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    specifications: [
      "75ml",
      "Eau de Parfum",
      "Evening fragrance",
      "Premium packaging",
    ],
    reviews: [
      {
        author: "Ruby Andrews",
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Leah Henderson",
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Xavier Wright",
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription:
      "Elegant fragrance with grapefruit, rose, and sandalwood notes",
  },
  {
    title: "Dior J'adore",
    brand: "Dior",
    price: 89.99,
    quantity: 98,
    soldQuantity: 0,
    rate: "3.8",
    discount: 14.72,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
    sku: "FRA-DIO-DIO-008",
    category: "fragrances",
    colors: ["gold"],
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    specifications: [
      "50ml",
      "Eau de Parfum",
      "Floral scent",
      "Luxury packaging",
    ],
    reviews: [
      {
        author: "Nicholas Bailey",
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Penelope Harper",
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Emma Miller",
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription:
      "Luxurious floral fragrance with ylang-ylang, rose, and jasmine",
  },
  {
    title: "Dolce Shine Eau de",
    brand: "Dolce & Gabbana",
    price: 69.99,
    quantity: 4,
    soldQuantity: 0,
    rate: "3.96",
    discount: 0.62,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
    sku: "FRA-DOL-DOL-009",
    category: "fragrances",
    colors: ["pink"],
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    specifications: [
      "100ml",
      "Eau de Toilette",
      "Fruity floral",
      "Youthful scent",
    ],
    reviews: [
      {
        author: "Mateo Bennett",
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nolan Gonzalez",
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Aurora Lawson",
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Vibrant fruity fragrance with mango and jasmine notes",
  },
  {
    title: "Gucci Bloom Eau de",
    brand: "Gucci",
    price: 79.99,
    quantity: 91,
    soldQuantity: 0,
    rate: "2.74",
    discount: 14.39,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
    sku: "FRA-GUC-GUC-010",
    category: "fragrances",
    colors: ["cream", "pink"],
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    specifications: [
      "30ml",
      "Eau de Parfum",
      "Modern floral",
      "Romantic scent",
    ],
    reviews: [
      {
        author: "Cameron Perez",
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Daniel Cook",
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Addison Wright",
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription:
      "Floral fragrance with tuberose, jasmine, and Rangoon creeper",
  },
  {
    title: "Annibale Colombo Bed",
    brand: "Annibale Colombo",
    price: 1899.99,
    quantity: 88,
    soldQuantity: 0,
    rate: "4.77",
    discount: 8.57,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
    sku: "FUR-ANN-ANN-011",
    category: "furniture",
    colors: ["walnut", "oak", "ebony"],
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    specifications: [
      "King size",
      "Solid wood",
      "Headboard included",
      "Assembly required",
    ],
    reviews: [
      {
        author: "Christopher West",
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Vivian Carter",
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Mason Wright",
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Luxurious and elegant bed frame",
  },
  {
    title: "Annibale Colombo Sofa",
    brand: "Annibale Colombo",
    price: 2499.99,
    quantity: 60,
    soldQuantity: 0,
    rate: "3.92",
    discount: 14.4,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
    sku: "FUR-ANN-ANN-012",
    category: "furniture",
    colors: ["cream", "grey", "navy"],
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    specifications: [
      "3-seater",
      "Premium fabric",
      "Solid wood frame",
      "Removable cushions",
    ],
    reviews: [
      {
        author: "Christian Perez",
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Lillian Bishop",
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Lillian Simmons",
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Sophisticated and comfortable sofa",
  },
  {
    title: "Bedside Table African Cherry",
    brand: "Furniture Co.",
    price: 299.99,
    quantity: 64,
    soldQuantity: 0,
    rate: "2.87",
    discount: 19.09,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
    sku: "FUR-FUR-BED-013",
    category: "furniture",
    colors: ["cherry", "mahogany"],
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    specifications: [
      "African cherry wood",
      "2 drawers",
      "Solid brass handles",
      "Assembly required",
    ],
    reviews: [
      {
        author: "Aaliyah Hanson",
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Liam Smith",
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Avery Barnes",
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Stylish bedside table in African Cherry",
  },
  {
    title: "Knoll Saarinen Executive Conference Chair",
    brand: "Knoll",
    price: 499.99,
    quantity: 26,
    soldQuantity: 0,
    rate: "4.88",
    discount: 2.01,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
    sku: "FUR-KNO-KNO-014",
    category: "furniture",
    colors: ["black", "white", "chrome"],
    description:
      "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    specifications: [
      "Ergonomic design",
      "Swivel base",
      "Adjustable height",
      "Premium materials",
    ],
    reviews: [
      {
        author: "Ella Cook",
        rating: 2,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Clara Berry",
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Elena Long",
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Modern ergonomic conference chair",
  },
  {
    title: "Wooden Bathroom Sink With Mirror",
    brand: "Bath Trends",
    price: 799.99,
    quantity: 7,
    soldQuantity: 0,
    rate: "3.59",
    discount: 8.8,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
    sku: "FUR-BAT-WOO-015",
    category: "furniture",
    colors: ["teak", "walnut"],
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    specifications: [
      "Solid wood countertop",
      "Ceramic basin",
      "LED mirror",
      "Water-resistant finish",
    ],
    reviews: [
      {
        author: "Logan Torres",
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Aria Parker",
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Dylan Wells",
        rating: 3,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Wooden bathroom sink with matching mirror",
  },
  {
    title: "Apple",
    brand: "Fresh Farm",
    price: 1.99,
    quantity: 8,
    soldQuantity: 0,
    rate: "4.19",
    discount: 12.62,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
    sku: "GRO-BRD-APP-016",
    category: "groceries",
    colors: ["red", "green"],
    description:
      "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
    specifications: ["Organic", "Gala variety", "1lb bag", "No preservatives"],
    reviews: [
      {
        author: "Sophia Brown",
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Scarlett Bowman",
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "William Gonzalez",
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Fresh crisp apples",
  },
  {
    title: "Beef Steak",
    brand: "Prime Cuts",
    price: 12.99,
    quantity: 86,
    soldQuantity: 0,
    rate: "4.47",
    discount: 9.61,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
    sku: "GRO-BRD-BEE-017",
    category: "groceries",
    colors: ["red"],
    description:
      "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
    specifications: ["Ribeye cut", "USDA Choice", "16oz", "Vacuum sealed"],
    reviews: [
      {
        author: "Eleanor Tyler",
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Alexander Jones",
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Natalie Harris",
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "High-quality beef steak",
  },
  {
    title: "Cat Food",
    brand: "Purrfect Nutrition",
    price: 8.99,
    quantity: 46,
    soldQuantity: 0,
    rate: "3.13",
    discount: 9.58,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
    sku: "GRO-BRD-FOO-018",
    category: "groceries",
    colors: ["brown"],
    description:
      "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
    specifications: ["Indoor formula", "5lb bag", "Grain-free", "With taurine"],
    reviews: [
      {
        author: "Noah Lewis",
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Ruby Andrews",
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Ethan Thompson",
        rating: 2,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Nutritious cat food",
  },
  {
    title: "Chicken Meat",
    brand: "Farm Fresh Poultry",
    price: 9.99,
    quantity: 97,
    soldQuantity: 0,
    rate: "3.19",
    discount: 13.7,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
    sku: "GRO-BRD-CHI-019",
    category: "groceries",
    colors: ["white", "pink"],
    description:
      "Fresh and tender chicken meat, suitable for various culinary preparations.",
    specifications: ["Boneless", "Skinless", "Breast cut", "1lb package"],
    reviews: [
      {
        author: "Mateo Bennett",
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Jackson Evans",
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Sadie Morales",
        rating: 3,
        comment: "Not worth the price!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Fresh tender chicken meat",
  },
  {
    title: "Cooking Oil",
    brand: "Pure Harvest",
    price: 4.99,
    quantity: 10,
    soldQuantity: 0,
    rate: "4.8",
    discount: 9.33,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
    sku: "GRO-BRD-COO-020",
    category: "groceries",
    colors: ["yellow"],
    description:
      "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
    specifications: ["Vegetable oil", "1 liter", "High smoke point", "Non-GMO"],
    reviews: [
      {
        author: "Victoria McDonald",
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Hazel Evans",
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Zoe Bennett",
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Versatile cooking oil",
  },
  {
    title: "Cucumber",
    brand: "Green Garden",
    price: 1.49,
    quantity: 84,
    soldQuantity: 0,
    rate: "4.07",
    discount: 0.16,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp",
    sku: "GRO-BRD-CUC-021",
    category: "groceries",
    colors: ["green"],
    description:
      "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
    specifications: [
      "English cucumber",
      "Hydroponic",
      "Per piece",
      "No wax coating",
    ],
    reviews: [
      {
        author: "Lincoln Kelly",
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Savannah Gomez",
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "James Davis",
        rating: 2,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Crisp hydrating cucumbers",
  },
  {
    title: "Dog Food",
    brand: "Canine Care",
    price: 10.99,
    quantity: 71,
    soldQuantity: 0,
    rate: "4.55",
    discount: 10.27,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp",
    sku: "GRO-BRD-FOO-022",
    category: "groceries",
    colors: ["brown", "orange"],
    description:
      "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
    specifications: [
      "Adult formula",
      "15lb bag",
      "With real chicken",
      "No artificial colors",
    ],
    reviews: [
      {
        author: "Nicholas Edwards",
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Zachary Lee",
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nova Cooper",
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Specially formulated dog food",
  },
  {
    title: "Eggs",
    brand: "Sunny Side Farms",
    price: 2.99,
    quantity: 9,
    soldQuantity: 0,
    rate: "2.53",
    discount: 11.05,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
    sku: "GRO-BRD-EGG-023",
    category: "groceries",
    colors: ["white", "brown"],
    description:
      "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
    specifications: ["Grade A", "Large eggs", "Dozen", "Cage-free"],
    reviews: [
      {
        author: "Penelope King",
        rating: 3,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Eleanor Tyler",
        rating: 3,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Benjamin Foster",
        rating: 4,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Fresh eggs",
  },
  {
    title: "Fish Steak",
    brand: "Ocean Fresh",
    price: 14.99,
    quantity: 74,
    soldQuantity: 0,
    rate: "3.78",
    discount: 4.23,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp",
    sku: "GRO-BRD-FIS-024",
    category: "groceries",
    colors: ["white", "pink"],
    description:
      "Quality fish steak, suitable for grilling, baking, or pan-searing.",
    specifications: ["Salmon steak", "Wild caught", "8oz each", "Fresh frozen"],
    reviews: [
      {
        author: "Caleb Perkins",
        rating: 2,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Isabella Jackson",
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nathan Dixon",
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Quality fish steak",
  },
  {
    title: "Green Bell Pepper",
    brand: "Veggie Garden",
    price: 1.29,
    quantity: 33,
    soldQuantity: 0,
    rate: "3.25",
    discount: 0.16,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp",
    sku: "GRO-BRD-GRE-025",
    category: "groceries",
    colors: ["green"],
    description:
      "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
    specifications: [
      "Large size",
      "Per piece",
      "Sweet flavor",
      "No pesticides",
    ],
    reviews: [
      {
        author: "Avery Carter",
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Henry Hill",
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Addison Wright",
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Fresh vibrant green bell pepper",
  },
  {
    title: "Green Chili Pepper",
    brand: "Spice Garden",
    price: 0.99,
    quantity: 3,
    soldQuantity: 0,
    rate: "3.66",
    discount: 1,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp",
    sku: "GRO-BRD-GRE-026",
    category: "groceries",
    colors: ["green"],
    description:
      "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
    specifications: ["Jalapeño peppers", "Medium heat", "Per piece", "Fresh"],
    reviews: [
      {
        author: "Luna Russell",
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Noah Lewis",
        rating: 1,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Clara Berry",
        rating: 3,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Spicy green chili pepper",
  },
  {
    title: "Honey Jar",
    brand: "Nature's Sweet",
    price: 6.99,
    quantity: 34,
    soldQuantity: 0,
    rate: "3.97",
    discount: 14.4,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
    sku: "GRO-BRD-HON-027",
    category: "groceries",
    colors: ["golden", "amber"],
    description:
      "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
    specifications: ["Raw honey", "16oz jar", "Pure", "No additives"],
    reviews: [
      {
        author: "Autumn Gomez",
        rating: 1,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Benjamin Wilson",
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nicholas Edwards",
        rating: 2,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Pure natural honey",
  },
  {
    title: "Ice Cream",
    brand: "Creamy Delights",
    price: 5.49,
    quantity: 27,
    soldQuantity: 0,
    rate: "3.39",
    discount: 8.69,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp",
    sku: "GRO-BRD-CRE-028",
    category: "groceries",
    colors: ["vanilla", "chocolate", "strawberry"],
    description:
      "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
    specifications: ["1 pint", "Vanilla bean", "Premium quality", "Dairy"],
    reviews: [
      {
        author: "Elijah Cruz",
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Jace Smith",
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Sadie Morales",
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Creamy delicious ice cream",
  },
  {
    title: "Juice",
    brand: "Fresh Squeezed",
    price: 3.99,
    quantity: 50,
    soldQuantity: 0,
    rate: "3.94",
    discount: 12.06,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp",
    sku: "GRO-BRD-JUI-029",
    category: "groceries",
    colors: ["orange", "apple", "grape"],
    description:
      "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
    specifications: [
      "Orange juice",
      "64oz carton",
      "No added sugar",
      "Pasteurized",
    ],
    reviews: [
      {
        author: "Nolan Gonzalez",
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Bella Grant",
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Aria Flores",
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Refreshing fruit juice",
  },
  {
    title: "Kiwi",
    brand: "Tropical Fresh",
    price: 2.49,
    quantity: 99,
    soldQuantity: 0,
    rate: "4.93",
    discount: 15.22,
    hasDiscount: true,
    imgurl:
      "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp",
    sku: "GRO-BRD-KIW-030",
    category: "groceries",
    colors: ["green", "brown"],
    description:
      "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
    specifications: [
      "New Zealand kiwi",
      "Per piece",
      "Sweet and tangy",
      "Rich in Vitamin C",
    ],
    reviews: [
      {
        author: "Emily Brown",
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Jackson Morales",
        rating: 2,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
      },
      {
        author: "Nora Russell",
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
      },
    ],
    shortDescription: "Nutrient-rich kiwi",
  },
];

//   {
//     title: "Wireless Mouse",
//     brand: "Logitech",
//     price: 25.99,
//     quantity: 100,
//     colors: ["Black", "Blue"],
//     description:
//       "Ergonomic wireless mouse with long battery life and precise optical sensor.",
//     shortDescription: "Comfortable wireless mouse",
//     specifications: ["2.4 GHz wireless", "Optical sensor", "USB receiver"],
//     imgurl: "https://images.pexels.com/photos/715688/pexels-photo-715688.jpeg", // generic product image
//     sku: "LOGI-MOUSE-001",
//     category: "Electronics",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Mechanical Keyboard RGB",
//     brand: "Corsair",
//     price: 89.99,
//     quantity: 50,
//     colors: ["Black", "RGB"],
//     description:
//       "High-performance mechanical keyboard with Cherry MX switches and customizable RGB backlight.",
//     shortDescription: "Gaming mechanical keyboard",
//     specifications: ["Cherry MX switches", "RGB backlight", "USB-C connection"],
//     imgurl: "https://images.pexels.com/photos/196655/pexels-photo-196655.jpeg",
//     sku: "COR-KB-002",
//     category: "Electronics",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Running Shoes",
//     brand: "Nike",
//     price: 120.0,
//     quantity: 200,
//     colors: ["Red", "Black", "White"],
//     description:
//       "Lightweight running shoes with breathable mesh and cushioned midsole for comfort on long runs.",
//     shortDescription: "Comfortable running shoes",
//     specifications: ["Breathable mesh upper", "Foam midsole", "Rubber outsole"],
//     imgurl:
//       "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
//     sku: "NIKE-RUN-003",
//     category: "Sportswear",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Classic Jeans Slim Fit",
//     brand: "Levis",
//     price: 59.99,
//     quantity: 120,
//     colors: ["Blue", "Dark Blue"],
//     description:
//       "Slim fit classic denim jeans with comfortable stretch and durable stitching.",
//     shortDescription: "Slim fit classic jeans",
//     specifications: ["98% cotton", "2% elastane", "Zip fly"],
//     imgurl:
//       "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
//     sku: "LEVI-JEAN-004",
//     category: "Apparel",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Stainless Steel Water Bottle 1L",
//     brand: "HydroFlex",
//     price: 19.5,
//     quantity: 300,
//     colors: ["Silver", "Matte Black"],
//     description:
//       "1‑liter insulated stainless steel water bottle — keeps drink cold for 24h or hot for 12h.",
//     shortDescription: "Insulated stainless water bottle 1L",
//     specifications: ["Double-wall insulation", "BPA-free", "Leak proof cap"],
//     imgurl:
//       "https://images.pexels.com/photos/1443776/pexels-photo-1443776.jpeg",
//     sku: "HYDRO-BOT-005",
//     category: "Home & Kitchen",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Bluetooth Speaker Portable",
//     brand: "SoundPulse",
//     price: 45.0,
//     quantity: 80,
//     colors: ["Black", "Gray"],
//     description:
//       "Compact portable Bluetooth speaker with 10h battery and deep bass sound.",
//     shortDescription: "Portable Bluetooth speaker",
//     specifications: ["Bluetooth 5.0", "10 h playtime", "Water-resistant"],
//     imgurl: "https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg",
//     sku: "SPKR-BT-006",
//     category: "Electronics",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Yoga Mat 6 mm",
//     brand: "FlexFit",
//     price: 29.99,
//     quantity: 150,
//     colors: ["Purple", "Green", "Black"],
//     description:
//       "6 mm thick non-slip yoga mat, ideal for yoga, pilates or general floor exercises.",
//     shortDescription: "Non‑slip yoga mat 6 mm",
//     specifications: ["6 mm thickness", "Non-slip", "Lightweight"],
//     imgurl:
//       "https://images.pexels.com/photos/3822986/pexels-photo-3822986.jpeg",
//     sku: "FLEX-YOGA-007",
//     category: "Sports & Fitness",
//     discount: 0,
//     hasDiscount: false,
//   },
//   {
//     title: "Stainless Steel Wrist Watch",
//     brand: "Timeless",
//     price: 150.0,
//     quantity: 40,
//     colors: ["Silver", "Gold"],
//     description:
//       "Elegant stainless steel wrist watch with quartz movement and water resistance up to 50m.",
//     shortDescription: "Stainless steel wrist watch",
//     specifications: ["Quartz movement", "Water resistant 50m", "Mineral glass"],
//     imgurl: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg",
//     sku: "TIME-WATCH-008",
//     category: "Accessories",
//     discount: 0,
//     hasDiscount: false,
//   },
// ];

// Seeder route or standalone invocation
async function seedProducts() {
  try {
    if ((await Product.find()).length === 0) {
      // await Product.deleteMany({});
      const created = await Product.insertMany(sampleProducts);
      console.log(
        "seeding done total products:",
        (await Product.find()).length
      );
    } else {
      console.log(
        "no seeding already products exist total products:",
        (await Product.find()).length
      );
    }
  } catch (err) {
    console.error("Error seeding products:", err);
  }
}

export default seedProducts;
